var fs = require('fs');
var content = fs.readFileSync('frontend/index.html', 'utf8');

var css = '.chat-panel{position:fixed;right:0;top:0;width:380px;height:100vh;background:#fff;box-shadow:-4px 0 20px rgba(0,0,0,.12);z-index:999;display:flex;flex-direction:column;transform:translateX(100%);transition:transform .3s ease}.chat-panel.open{transform:translateX(0)}.chat-panel-header{background:#1a237e;color:#fff;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;flex-shrink:0}.chat-panel-header h3{font-size:16px}.chat-close-btn{background:none;border:none;color:#fff;font-size:20px;cursor:pointer}.chat-layout{display:flex;flex:1;overflow:hidden}.chat-patient-list{width:160px;border-right:1px solid #e0e0e0;overflow-y:auto;flex-shrink:0}.chat-patient-item{padding:12px 10px;cursor:pointer;border-bottom:1px solid #f0f0f0}.chat-patient-item:hover,.chat-patient-item.active{background:#e8f0fe}.chat-patient-item .pt-name{font-size:13px;font-weight:600;color:#222;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-patient-item .pt-last{font-size:11px;color:#888;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-patient-item .pt-meta{display:flex;justify-content:space-between;align-items:center;margin-top:4px}.unread-badge{background:#1a73e8;color:#fff;border-radius:50%;width:18px;height:18px;font-size:10px;font-weight:700;display:flex;align-items:center;justify-content:center}.priority-dot{width:8px;height:8px;border-radius:50%}.priority-urgent{background:#ef4444}.priority-high{background:#f97316}.priority-normal{background:#22c55e}.priority-low{background:#94a3b8}.chat-main{flex:1;display:flex;flex-direction:column;overflow:hidden}.chat-main-header{padding:12px 14px;border-bottom:1px solid #e0e0e0;flex-shrink:0}.chat-main-header .pt-name{font-weight:600;font-size:14px}.chat-main-header .pt-id{font-size:12px;color:#888}.chat-messages{flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:8px;background:#f8fafc}.chat-bubble{max-width:85%;padding:8px 12px;border-radius:14px;font-size:13px;line-height:1.5}.chat-bubble.patient{background:#e8f0fe;color:#222;align-self:flex-start;border-bottom-left-radius:4px}.chat-bubble.staff{background:#1a73e8;color:#fff;align-self:flex-end;border-bottom-right-radius:4px}.chat-bubble .meta{font-size:10px;opacity:.7;margin-top:3px}.chat-priority-row{display:flex;gap:6px;padding:8px 12px;border-top:1px solid #e0e0e0;flex-shrink:0}.priority-btn{flex:1;padding:4px;border-radius:6px;border:2px solid #e0e0e0;background:#fff;font-size:11px;cursor:pointer;font-weight:600}.priority-btn.selected{border-color:#1a73e8;background:#e8f0fe;color:#1a73e8}.chat-input-row{display:flex;gap:6px;padding:10px 12px;border-top:1px solid #e0e0e0;flex-shrink:0}.chat-input-row textarea{flex:1;resize:none;height:38px;padding:8px 12px;border:2px solid #e0e0e0;border-radius:20px;font-size:13px;font-family:inherit}.chat-input-row textarea:focus{outline:none;border-color:#1a73e8}.chat-send-btn{background:#1a73e8;color:#fff;border:none;border-radius:50%;width:38px;height:38px;cursor:pointer;font-size:16px;display:flex;align-items:center;justify-content:center}.chat-send-btn:hover{background:#1558b0}.chat-empty{text-align:center;color:#aaa;font-size:13px;margin:auto}.chat-nav-btn{position:fixed;bottom:24px;right:24px;background:#1a237e;color:#fff;border:none;border-radius:50px;padding:12px 20px;font-size:15px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.2);z-index:998;display:flex;align-items:center;gap:8px}.total-badge{background:#ef4444;color:#fff;border-radius:50%;width:20px;height:20px;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center}';

var html = [
'<button class="chat-nav-btn" onclick="toggleChatPanel()">💬 Messages',
'<span class="total-badge" id="staff-total-badge" style="display:none">0</span></button>',
'<div class="chat-panel" id="staff-chat-panel">',
'<div class="chat-panel-header"><h3>💬 Patient Messages</h3>',
'<button class="chat-close-btn" onclick="toggleChatPanel()">✕</button></div>',
'<div class="chat-layout">',
'<div class="chat-patient-list" id="staff-patient-list">',
'<div style="padding:12px;font-size:12px;color:#aaa;text-align:center">Loading...</div></div>',
'<div class="chat-main" id="staff-chat-main">',
'<div class="chat-messages"><div class="chat-empty">Select a patient</div></div>',
'</div></div></div>',
'<script>',
'(function(){',
'var sel=null,prio="normal",tok=localStorage.getItem("token"),poll=null;',
'function api(path,opts){',
'opts=opts||{};',
'return fetch("/api"+path,Object.assign({},opts,{headers:Object.assign({"Authorization":"Bearer "+tok,"Content-Type":"application/json"},opts.headers||{})})).then(function(r){return r.json();});',
'}',
'window.toggleChatPanel=function(){',
'var p=document.getElementById("staff-chat-panel");',
'var isOpen=p.classList.toggle("open");',
'if(isOpen){loadList();if(!poll)poll=setInterval(refresh,8000);}',
'else{if(poll){clearInterval(poll);poll=null;}}',
'};',
'function loadList(){',
'api("/chat/patients").then(function(pts){',
'if(!Array.isArray(pts))return;',
'var total=pts.reduce(function(s,p){return s+(p.unread_count||0);},0);',
'var b=document.getElementById("staff-total-badge");',
'if(total>0){b.textContent=total;b.style.display="flex";}else{b.style.display="none";}',
'var list=document.getElementById("staff-patient-list");',
'if(!pts.length){list.innerHTML="<div style=\'padding:12px;font-size:12px;color:#aaa;text-align:center\'>No messages</div>";return;}',
'list.innerHTML=pts.map(function(p){',
'var pc=p.highest_priority?"priority-"+p.highest_priority:"priority-normal";',
'var last=p.last_message?p.last_message.substring(0,28):"No messages";',
'var badge=p.unread_count>0?"<span class=\'unread-badge\'>"+p.unread_count+"</span>":"";',
'return "<div class=\'chat-patient-item"+(sel==p.id?" active":"")+"\'"+',
'" onclick=\'selectPt("+p.id+",\\\""+p.name+"\\\",\\\""+p.patient_id+"\\\")\'>"+',
'"<div class=\'pt-name\'>"+p.name+"</div>"+',
'"<div class=\'pt-last\'>"+last+"</div>"+',
'"<div class=\'pt-meta\'><span class=\'priority-dot "+pc+"\'></span>"+badge+"</div></div>";',
'}).join("");',
'}).catch(function(){});}',
'window.selectPt=function(id,name,pid){',
'sel=id;',
'api("/chat/read/"+id,{method:"PUT"}).then(loadList);',
'var main=document.getElementById("staff-chat-main");',
'main.innerHTML=',
'"<div class=\'chat-main-header\'><div class=\'pt-name\'>"+name+"</div><div class=\'pt-id\'>"+pid+"</div></div>"+',
'"<div class=\'chat-messages\' id=\'scm\'></div>"+',
'"<div class=\'chat-priority-row\'>"+',
'"<span style=\'font-size:11px;color:#888;align-self:center\'>Priority:</span>"+',
'"<button class=\'priority-btn selected\' id=\'pn\' onclick=\'sp(\\\"normal\\\")\'>Normal</button>"+',
'"<button class=\'priority-btn\' id=\'ph\' onclick=\'sp(\\\"high\\\")\' style=\'color:#f97316\'>High</button>"+',
'"<button class=\'priority-btn\' id=\'pu\' onclick=\'sp(\\\"urgent\\\")\' style=\'color:#ef4444\'>Urgent</button></div>"+',
'"<div class=\'chat-input-row\'>"+',
'"<textarea id=\'sci\' placeholder=\'Type reply...\' onkeydown=\'sk(event)\'></textarea>"+',
'"<button class=\'chat-send-btn\' onclick=\'ss()\'>➤</button></div>";',
'prio="normal";loadMsgs();',
'};',
'window.sp=function(p){',
'prio=p;',
'["normal","high","urgent"].forEach(function(x){',
'var b=document.getElementById("p"+x[0]);',
'if(b)b.classList.toggle("selected",x===p);',
'});};',
'function loadMsgs(){',
'if(!sel)return;',
'api("/chat/patients/"+sel).then(function(msgs){',
'var box=document.getElementById("scm");',
'if(!box)return;',
'if(!Array.isArray(msgs)||!msgs.length){box.innerHTML="<div class=\'chat-empty\'>No messages yet</div>";return;}',
'box.innerHTML=msgs.map(function(m){',
'var ip=m.sender_role==="patient";',
'var t=new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});',
'var name=ip?"Patient":(m.staff_name||"Staff");',
'return "<div class=\'chat-bubble "+(ip?"patient":"staff")+"\'><div>"+m.message.replace(/\\n/g,"<br>")+"</div><div class=\'meta\'>"+name+" · "+t+"</div></div>";',
'}).join("");',
'box.scrollTop=box.scrollHeight;',
'}).catch(function(){});}',
'window.ss=function(){',
'var inp=document.getElementById("sci");',
'if(!inp||!sel)return;',
'var msg=inp.value.trim();',
'if(!msg)return;',
'inp.value="";',
'api("/chat/send",{method:"POST",body:JSON.stringify({patient_id:sel,message:msg,priority:prio})}).then(function(){loadMsgs();loadList();}).catch(function(){});',
'};',
'window.sk=function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ss();}};',
'function refresh(){loadList();if(sel)loadMsgs();}',
'setInterval(function(){',
'if(!tok)return;',
'api("/chat/unread-total").then(function(d){',
'var b=document.getElementById("staff-total-badge");',
'if(d.total>0){b.textContent=d.total;b.style.display="flex";}else{b.style.display="none";}',
'}).catch(function(){});',
'},15000);',
'})();',
'<\/script>'
].join('');

content = content.replace('</style>', css + '\n</style>');
content = content.replace('</body>', html + '\n</body>');
fs.writeFileSync('frontend/index.html', content, 'utf8');
console.log('✅ Step 5 done');
